{% set name = "pystache" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystache-{{ version }}.tar.gz
  sha256: 9f238d5a06f18843e0d491d8e4e292dc03fed6a54cb0a5c34be37a3faa973174

build:
  entry_points:
    - pystache=pystache.commands.render:main
    - pystache-test=pystache.commands.test:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    # only required for py<310 but want to stay noarch: python
    - importlib-metadata >=4.6

test:
  imports:
    - pystache
  commands:
    - pip check
    - pip show pystache
    - "pip show {{ name }} | grep -Fx 'Version: {{ version }}' || true"
    - pystache --help
    - pystache-test --help
  requires:
    - pip

about:
  home: https://github.com/PennyDreadfulMTG/pystache
  summary: Mustache for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PennyDreadfulMTG/pystache
  doc_url: https://github.com/PennyDreadfulMTG/pystache/blob/master/README.rst

extra:
  recipe-maintainers:
    - xylar
    - kwilcox
    - jan-janssen
