{% set name = "pystache" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystache-{{ version }}.tar.gz
  sha256: 9f238d5a06f18843e0d491d8e4e292dc03fed6a54cb0a5c34be37a3faa973174

build:
  entry_points:
    - pystache=pystache.commands.render:main
    - pystache-test=pystache.commands.test:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pystache
  commands:
    - pip check
    - pystache --help
    - pystache-test --help
  requires:
    - pip

about:
  home: https://github.com/sarnold/pystache
  summary: Mustache for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - jan-janssen
