{% set name = "pystache" %}
{% set version = "0.5.6" %}
{% set build = 0 %}
{% set sha256 = "4c447356dbc36d632a39caeaac7baa9c47ba8ca3cd2928eb5f0fd0ceff3ef87f" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/sarnold/pystache/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    noarch: python
    entry_points:
        - pystache = pystache.commands.render:main
        - pystache-test = pystache.commands.test:main

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - pystache
        - pystache.commands
        - pystache.tests
        - pystache.tests.data
        - pystache.tests.data.locator
        - pystache.tests.examples

    commands:
        - pystache --help
        - pystache-test

about:
    home: http://github.com/sarnold/pystache
    license: MIT
    license_file: LICENSE
    summary: 'Mustache for Python'
    doc_url: "https://github.com/sarnold/pystache/blob/master/README.md"
    dev_url: "https://github.com/sarnold/pystache"

extra:
    recipe-maintainers:
        - kwilcox
        - sarnold
