{% set name = "pystache" %}
{% set version = "0.6.0" %}
{% set build = 0 %}
{% set sha256 = "1d7fe339e51ce8cc76489de17df72c951c3fd81907c5a64fbd46aac35a9dad5d" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/sarnold/pystache/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    noarch: python
    entry_points:
        - pystache = pystache.commands.render:main
        - pystache-test = pystache.commands.test:main

requirements:
    host:
        - python >=3.6
        - pip

    run:
        - python >=3.6

test:
    imports:
        - pystache
        - pystache.commands
        - pystache.tests
        - pystache.tests.data
        - pystache.tests.data.locator
        - pystache.tests.examples

    commands:
        - pystache --help
        - pystache-test

about:
    home: http://github.com/sarnold/pystache
    license: MIT
    license_file: LICENSE
    summary: 'Mustache for Python'
    doc_url: "https://github.com/sarnold/pystache/blob/master/README.md"
    dev_url: "https://github.com/sarnold/pystache"

extra:
    recipe-maintainers:
        - kwilcox
        - sarnold
