{% set name = "pystache" %}
{% set version = "0.6.0" %}
{% set build = 0 %}
{% set md5 = "c834ab23ec0d4a0e47cfa281bf7bfcd1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  entry_points:
    - pystache = pystache.commands.render:main
    - pystache-test = pystache.commands.test:main

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pystache
    - pystache.commands
    - pystache.tests
    - pystache.tests.data
    - pystache.tests.data.locator
    - pystache.tests.examples

  commands:
    - pystache --help
    - pystache-test

about:
  home: http://github.com/defunkt/pystache
  license: MIT
  license_file: LICENSE
  summary: Mustache for Python

extra:
  recipe-maintainers:
    - kwilcox
