{% set name = "pystache" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pystache-{{ version }}.tar.gz
  sha256: 55d8bb5aac450389369584b1627cecbe9069e13a09471a8fe783c44b64e94d5a

build:
  entry_points:
    - pystache=pystache.commands.render:main
    - pystache-test=pystache.commands.test:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    # only required for py<310 but want to stay noarch: python
    - importlib-metadata >=4.6

test:
  imports:
    - pystache
  commands:
    - pip check
    - pip show pystache
    - "pip show {{ name }} | grep -Fx 'Version: {{ version }}'"
    - pystache --help
    - pystache-test --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PennyDreadfulMTG/pystache
  summary: Mustache for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PennyDreadfulMTG/pystache
  doc_url: https://github.com/PennyDreadfulMTG/pystache/blob/master/README.rst

extra:
  recipe-maintainers:
    - xylar
    - kwilcox
    - jan-janssen
